"use client";

import Link from "next/link";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { guestTitle } from "@/lib/guest-title";
import { QuestionAtmosphere } from "@/components/question-atmosphere";
import { MagicalBackground } from "@/components/magical-world";
import { QuestionProgress } from "@/components/question-progress";

type BonusPrompt = { id: string; prompt: string };
type Question = { id: string; position: number; kind: "choice" | "bonus"; prompt: string; media: { type?: "image" | "emoji"; src?: string; clues?: string; displayClues?: string }; options: Array<string | BonusPrompt>; timeLimitSeconds: number; reveal?: { correctOption?: string; correctAnswers?: string[] } | null };
type ScoreRow = { nickname: string; score: number; rank: number };
type PlayerSummary = { player: ScoreRow; leaderboard: ScoreRow[]; currentResponse?: { option?: string; answers?: string[] } | null };
type State = { room: { code: string; status: "lobby" | "question" | "reveal" | "paused" | "finished"; currentPosition: number; deadlineAt: string | null }; question: Question | null; summary?: PlayerSummary | null; summaryError?: string | null };

export default function PlayPage() {
  const [room, setRoom] = useState(""); const [state, setState] = useState<State | null>(null); const [selected, setSelected] = useState<number | null>(null); const [answers, setAnswers] = useState<string[]>(Array(10).fill("")); const [submitted, setSubmitted] = useState(false); const [sending, setSending] = useState(false); const [message, setMessage] = useState("กำลังเชื่อมต่อกับห้อง…"); const [now, setNow] = useState(Date.now()); const ranks = useRef<Record<string, number>>({}); const refreshInFlight = useRef(false); const refreshVersion = useRef(0);
  const nickname = typeof window === "undefined" ? "Guest" : localStorage.getItem("jixgo-nickname") || "Guest";
  const refresh = useCallback(async (code: string) => {
    if (refreshInFlight.current) return;
    refreshInFlight.current = true;
    const version = ++refreshVersion.current;
    const controller = new AbortController();
    const timeout = window.setTimeout(() => controller.abort(), 7000);
    try {
      const response = await fetch(`/api/game/state?room=${encodeURIComponent(code)}&t=${Date.now()}`, { cache: "no-store", signal: controller.signal });
      if (!response.ok) {
        setMessage(response.status === 503 ? "ระบบเกมจริงยังไม่ได้เชื่อม Supabase" : "เชื่อมต่อห้องไม่สำเร็จ · กำลังลองใหม่");
        return;
      }
      const next = await response.json() as State;
      if (version !== refreshVersion.current || !next.room) return;
      setState(current => {
        if (current?.question?.id !== next.question?.id) {
          setSelected(null); setAnswers(Array(10).fill("")); setSubmitted(false); setSending(false);
        }
        return next;
      });
      setMessage("");
    } catch (error) {
      if ((error as Error).name !== "AbortError") setMessage("การเชื่อมต่อสะดุด · กำลังลองใหม่");
    } finally {
      window.clearTimeout(timeout);
      refreshInFlight.current = false;
    }
  }, []);
  useEffect(() => { const code = new URLSearchParams(window.location.search).get("room")?.trim().toUpperCase() || ""; setRoom(code); if (!code) { setMessage("ต้องเข้าร่วมห้องก่อนเริ่มเล่น"); return; } void refresh(code); const poll = window.setInterval(() => void refresh(code), 1000); const clock = window.setInterval(() => setNow(Date.now()), 250); return () => { window.clearInterval(poll); window.clearInterval(clock); }; }, [refresh]);
  const question = state?.question; const summary = state?.summary ?? null; const seconds = useMemo(() => state?.room.deadlineAt ? Math.max(0, Math.ceil((new Date(state.room.deadlineAt).getTime() - now) / 1000)) : 0, [state?.room.deadlineAt, now]); const canAnswer = state?.room.status === "question" && seconds > 0 && !submitted && !sending;
  async function submit(response: { option?: string; answers?: string[] }) { if (!room || !canAnswer) return; setSending(true); setMessage("กำลังล็อกคำตอบ…"); try { const result = await fetch("/api/game/answer", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ room, response }) }); if (!result.ok) { setMessage("ส่งคำตอบไม่สำเร็จหรือหมดเวลาแล้ว"); return; } setSubmitted(true); setMessage("ส่งคำตอบแล้ว · รอเฉลยอัตโนมัติ"); } finally { setSending(false); } }
  if (state?.room.status === "finished") return <Finish nickname={nickname} summary={summary} summaryError={state?.summaryError} ranks={ranks.current} />;
  if (!question || (state?.room.status !== "question" && state?.room.status !== "reveal")) return <Waiting room={room} message={message} />;
  if (state.room.status === "reveal") return <Reveal question={question} selected={selected} submitted={submitted} summary={summary} summaryError={state.summaryError} ranks={ranks.current} />;
  return <main className="page-shell question-screen"><QuestionAtmosphere /><section className="shell-content player-shell"><QuestionProgress current={question.position} /><div className="topbar player-topbar"><span className="question-number">QUESTION {String(question.position).padStart(2, "0")} / 20 · LIVE</span><span className={`timer ${seconds < 10 ? "danger" : ""}`}><small>TIME</small><strong>{seconds}</strong><em>SEC</em></span></div><div className={`panel question-card player-question-card ${question.kind === "bonus" ? "bonus-card" : ""}`}>{question.kind === "choice" ? <Choice question={question} selected={selected} disabled={!canAnswer} choose={(index) => { setSelected(index); void submit({ option: String(question.options[index]) }); }} /> : <Bonus question={question} answers={answers} disabled={!canAnswer} change={(i, value) => setAnswers(current => current.map((answer, index) => index === i ? value : answer))} submit={() => void submit({ answers })} />}<div className={`answer-status ${submitted ? "submitted" : seconds === 0 ? "expired" : ""}`}>{sending ? "กำลังล็อกคำตอบ…" : submitted ? message : seconds === 0 ? "หมดเวลาแล้ว · เฉลยจะแสดงใน 3 วินาที" : "คำตอบจะถูกล็อกเมื่อส่งหรือหมดเวลา"}</div><Link className="back-link player-exit" href="/">ออกจากเกม</Link></div></section></main>;
}

function Choice({ question, selected, disabled, choose }: { question: Question; selected: number | null; disabled: boolean; choose: (index: number) => void }) { const choices = question.options as string[]; const media = question.media; return <>{media.type === "emoji" ? <div className="emoji-question-frame"><div className="emoji-question-line">{media.displayClues ?? media.clues}</div></div> : <div className="question-image-frame"><img className="question-image" src={media.src} alt="ภาพประกอบคำถาม" /></div>}<h1 className="question-text question-prompt-banner">{question.prompt}</h1><div className="choices">{choices.map((choice, index) => <button className={`choice ${selected === index ? "selected" : ""}`} key={choice} disabled={disabled} onClick={() => choose(index)}><span className="choice-key">{String.fromCharCode(65 + index)}</span><span>{choice}</span></button>)}</div></>; }
function Bonus({ question, answers, disabled, change, submit }: { question: Question; answers: string[]; disabled: boolean; change: (index: number, value: string) => void; submit: () => void }) { const clues = question.options as BonusPrompt[]; return <><div className="bonus-heading"><span className="bonus-kicker">✦ FINAL SPELL · 60 SEC ✦</span><h1>{question.prompt}</h1><p>เติมชื่อเพลงให้ครบทุกตัวอักษร แล้วส่งคำตอบทั้ง 10 เพลง</p></div><div className="bonus-rule">คำตอบต้องสะกดตรงทุกตัวอักษร · ระบบตรวจบน server</div><div className="bonus-grid">{clues.map((clue, index) => <label className="bonus-entry" key={clue.id}><span className="bonus-id">{clue.id}</span><span className="bonus-clue">{clue.prompt}</span><input value={answers[index] ?? ""} onChange={event => change(index, event.target.value)} placeholder="พิมพ์ชื่อเพลง" disabled={disabled} autoComplete="off" /></label>)}</div><button className="button primary bonus-submit" disabled={disabled} onClick={submit}>ส่งคาถาทั้ง 10 เพลง ✦</button></>; }
function Reveal({ question, selected, submitted, summary, summaryError, ranks }: { question: Question; selected: number | null; submitted: boolean; summary: PlayerSummary | null; summaryError?: string | null; ranks: Record<string, number> }) { const correct = question.reveal?.correctOption; const bonusAnswers = question.reveal?.correctAnswers; const own = summary?.currentResponse?.option ?? (selected === null ? null : String(question.options[selected])); const isCorrect = own === correct; const bonusClues = question.options as BonusPrompt[]; const bonusResponses = summary?.currentResponse?.answers ?? []; const hasPositiveResult = question.kind === "bonus" ? bonusAnswers?.some((answer, index) => bonusResponses[index] === answer) : isCorrect; const encouragement = hasPositiveResult ? "เก่งมากเลย ✨ ข้อต่อไปเอาอีกนะ" : "ไม่เป็นไรน้า ✨ ข้อต่อไปเอาใหม่"; return <main className="page-shell"><section className="shell-content player-shell"><div className="reveal-wrap"><div className={`reveal-card ${isCorrect ? "correct" : "wrong"}`}><img className="reveal-event-logo" src="/assets/logo-jixgo-full.png" alt="JIXGO Magical 24" /><span className="reveal-icon">{isCorrect ? "✦" : "✧"}</span><div className="eyebrow-small">QUESTION {String(question.position).padStart(2, "0")} · REVEAL</div><h1>{question.kind === "bonus" ? "เฉลย Bonus Magic Time" : isCorrect ? "คำตอบถูกต้อง!" : submitted ? "ยังไม่ใช่คำตอบนี้" : "หมดเวลาแล้ว"}</h1><p className={`answer-encouragement ${hasPositiveResult ? "positive" : "gentle"}`}>{encouragement}</p>{correct ? <><p>คำตอบที่ถูกต้องคือ</p><strong className="reveal-answer">{correct}</strong></> : bonusAnswers ? <ol className="bonus-reveal-list">{bonusAnswers.map((answer, index) => { const response = bonusResponses[index] ?? ""; const isRight = response === answer; return <li className={isRight ? "bonus-correct" : "bonus-wrong"} key={`${bonusClues[index]?.id ?? index}-${answer}`}><span className="bonus-result-icon">{isRight ? "✓" : "✕"}</span><span><b>{bonusClues[index]?.id ?? `20.${index + 1}`}</b> · {bonusClues[index]?.prompt}<small>{isRight ? "ตอบถูก" : `ตอบ: ${response || "ไม่ได้ตอบ"}`}</small></span><strong>{isRight ? "ถูกต้อง" : `เฉลย: ${answer}`}</strong></li>; })}</ol> : <p>กำลังเปิดเฉลย…</p>}</div><Scoreboard summary={summary} summaryError={summaryError} ranks={ranks} /></div></section></main>; }
function Scoreboard({ summary, summaryError, ranks, final = false }: { summary: PlayerSummary | null; summaryError?: string | null; ranks: Record<string, number>; final?: boolean }) { if (!summary) return <p className="waiting scoreboard-error">{summaryError?.includes("PLAYER_NOT_FOUND") ? "ข้อมูลผู้เล่นของห้องนี้ถูกรีเซ็ตแล้ว · กลับไปเข้าร่วมห้องใหม่" : "กำลังโหลดคะแนนจากห้อง…"}</p>; const medal = (rank: number) => rank === 1 ? "🥇" : rank === 2 ? "🥈" : rank === 3 ? "🥉" : null; return <section className="scoreboard panel"><div className="eyebrow-small">{final ? "FINAL LEADERBOARD" : "LIVE SCOREBOARD"}</div><div className="my-rank"><span>อันดับของคุณ</span><strong>#{summary.player.rank}</strong><em>{summary.player.score} คะแนน</em></div><ol className="rank-list score-list">{summary.leaderboard.map(row => { const before = ranks[row.nickname]; const delta = before ? before - row.rank : 0; ranks[row.nickname] = row.rank; return <li className={delta ? "rank-shift" : ""} key={row.nickname}><span>{final && medal(row.rank) ? <b className="rank-medal" aria-label={`อันดับ ${row.rank}`}>{medal(row.rank)}</b> : null}#{row.rank} {row.nickname}{delta > 0 ? <b className="rank-up"> ▲{delta}</b> : delta < 0 ? <b className="rank-down"> ▼{Math.abs(delta)}</b> : null}</span><strong>{row.score}</strong></li>; })}</ol>{!final && <p className="waiting">รอ Host เริ่มข้อถัดไป ✦</p>}</section>; }
function Waiting({ room, message }: { room: string; message: string }) { return <main className="page-shell lobby-world-shell waiting-world"><MagicalBackground /><section className="shell-content"><div className="panel lobby-center finish-card"><div className="eyebrow-small">LIVE ROOM {room || "—"}</div><div className="waiting-orb">✦</div><h1 className="title">รอประตูเวทมนตร์เปิด</h1><p className="waiting">{message}</p><p className="waiting-hint">กำลังเตรียมคำถามแรกให้คุณ…</p><Link className="back-link" href="/join">กลับไปเข้าร่วมห้อง</Link></div></section></main>; }
function Finish({ nickname, summary, summaryError, ranks }: { nickname: string; summary: PlayerSummary | null; summaryError?: string | null; ranks: Record<string, number> }) { return <main className="page-shell"><section className="shell-content player-shell"><div className="panel lobby-center finish-card"><div className="eyebrow-small">QUEST COMPLETE · {nickname.toUpperCase()}</div><h1 className="title">จบการเดินทางแล้ว ✦</h1>{summary ? <><div className="final-score"><span>{guestTitle(nickname)}</span><strong>{summary.player.score}</strong><em>คะแนน · อันดับ #{summary.player.rank}</em></div><Scoreboard summary={summary} ranks={ranks} final /></> : <Scoreboard summary={summary} summaryError={summaryError} ranks={ranks} final />}<Link className="button primary" href="/">กลับหน้าแรก</Link></div></section></main>; }
