"use client";

import Link from "next/link";
import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";

type RoomStatus = "lobby" | "question" | "reveal" | "paused" | "finished";
type HostState = { state: { room: { code: string; status: RoomStatus; currentPosition: number; deadlineAt?: string | null } }; playerCount: number; readyCount?: number; answerCount?: number; leaderboard: { nickname: string; score: number }[] };
const statusCopy: Record<RoomStatus, string> = { lobby: "กำลังรอเปิดประตู", question: "กำลังตอบคำถาม", reveal: "กำลังแสดงเฉลย", paused: "เกมพักอยู่", finished: "เกมจบแล้ว" };

export default function HostDashboard() {
  const [room, setRoom] = useState("142426"); const [data, setData] = useState<HostState | null>(null); const [showAll, setShowAll] = useState(false); const [message, setMessage] = useState("กำลังเชื่อมต่อห้องจริง…"); const [busy, setBusy] = useState(false); const [now, setNow] = useState(Date.now());
  const refresh = useCallback(async () => { if (!room) return; try { const response = await fetch(`/api/game/host/state?room=${encodeURIComponent(room)}&t=${Date.now()}`, { cache: "no-store" }); const payload = await response.json().catch(() => ({})); if (!response.ok) { setData(null); setMessage(payload.error === "GAME_NOT_CONFIGURED" ? "ยังไม่ได้ตั้งค่า Supabase ใน Vercel" : payload.error === "HOST_UNAUTHORIZED" ? "รหัสนี้ยังไม่ได้เตรียมห้อง หรือรหัส Host ไม่ตรง — กด “เตรียมห้อง / seed คำถาม” สำหรับรหัสนี้" : "ยังไม่พบห้องจริง — กด “เตรียมห้อง” หลังรัน migration"); return; } setData(payload as HostState); setMessage("เชื่อมต่อห้องจริงแล้ว · คะแนนอัปเดตอัตโนมัติ"); } catch { setMessage("การเชื่อมต่อสะดุด · กำลังลองใหม่"); } }, [room]);
  useEffect(() => { void refresh(); const timer = window.setInterval(() => void refresh(), 1500); const clock = window.setInterval(() => setNow(Date.now()), 250); return () => { window.clearInterval(timer); window.clearInterval(clock); }; }, [refresh]);
  async function prepare(event: FormEvent) { event.preventDefault(); setBusy(true); setMessage(`กำลัง seed คำถามและเตรียมห้อง ${room}…`); const response = await fetch("/api/game/setup", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ room }) }); const payload = await response.json().catch(() => ({})); setBusy(false); if (!response.ok) { setMessage(payload.error === "GAME_NOT_CONFIGURED" ? "ยังไม่ได้ตั้งค่า Supabase ใน Vercel" : `เตรียมห้องไม่สำเร็จ: ${payload.error ?? "ตรวจ session หรือ migration"}`); return; } setRoom(payload.room); setMessage(`เตรียมห้อง ${payload.room} พร้อมคำถาม 1–20 แล้ว · คะแนนเริ่มที่ 0`); }
  function generateRoomCode() { const next = String(Math.floor(100000 + Math.random() * 900000)); setRoom(next); setData(null); setMessage(`สร้างรหัสใหม่ ${next} แล้ว · กด “เตรียมห้อง / seed คำถาม” เพื่อเปิดห้อง`); }
  async function command(position: number, status: RoomStatus) { setBusy(true); const response = await fetch("/api/game/host", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ room, position, status }) }); const payload = await response.json().catch(() => ({})); setBusy(false); if (!response.ok) { setMessage(payload.error === "GAME_NOT_CONFIGURED" ? "ยังไม่ได้ตั้งค่า Supabase ใน Vercel" : "สั่งเกมไม่สำเร็จ: session หมดอายุหรือสถานะห้องเปลี่ยนแล้ว"); return; } setMessage(status === "question" ? `เริ่มข้อ ${position} แล้ว` : status === "finished" ? "ปิดเกมแล้ว · leaderboard พร้อมประกาศ" : "อัปเดตสถานะเกมแล้ว"); void refresh(); }
  async function resetTestRoom() { if (room !== "142426" || !window.confirm("รีเซ็ตห้องทดสอบ 142426? ผู้เล่น คำตอบ และคะแนนทั้งหมดของห้องนี้จะถูกล้าง")) return; setBusy(true); setMessage("กำลังรีเซ็ตห้องทดสอบ…"); const response = await fetch("/api/game/reset", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ room }) }); const payload = await response.json().catch(() => ({})); setBusy(false); if (!response.ok) { setMessage(`รีเซ็ตห้องไม่สำเร็จ: ${payload.error ?? "session หมดอายุ"}`); return; } setMessage("รีเซ็ตห้องทดสอบแล้ว · กลับสู่ข้อ 1 และล้างคะแนนทั้งหมด"); void refresh(); }
  async function logout() { await fetch("/api/game/host/logout", { method: "POST" }); window.location.reload(); }
  const game = data?.state.room; const position = game?.currentPosition ?? 1; const leaderboard = data?.leaderboard ?? []; const displayedRanks = showAll ? leaderboard : leaderboard.slice(0, 5); const seconds = useMemo(() => game?.deadlineAt ? Math.max(0, Math.ceil((new Date(game.deadlineAt).getTime() - now) / 1000)) : 0, [game?.deadlineAt, now]);
  return <main className="page-shell"><section className="shell-content"><div className="topbar"><div><div className="eyebrow-small">HOST CONTROL · PRIVATE</div><h1 className="title">JIXGO Magical 24</h1></div><div className="topbar-actions"><Link className="back-link" href="/preview">ดู Preview คำถาม</Link><button className="text-button" onClick={() => void logout()}>ออกจาก Host</button></div></div><div className="host-grid"><div className="panel"><form className="form-stack" onSubmit={prepare}><label>รหัสห้อง<input className="code-input" value={room} onChange={(event) => setRoom(event.target.value.replace(/\D/g, "").slice(0, 6))} inputMode="numeric" maxLength={6} required /></label><div className="host-room-actions"><button className="button ghost" type="button" disabled={busy} onClick={generateRoomCode}>สุ่มรหัสห้องใหม่</button><button className="button ghost" type="submit" disabled={busy}>เตรียมห้อง / seed คำถาม</button></div></form><p className={`answer-status ${data ? "submitted" : ""}`}>{message}</p><HostMonitor game={game} players={data?.playerCount ?? 0} ready={data?.readyCount ?? 0} answered={data?.answerCount ?? 0} seconds={seconds} /><div className="control-grid"><button className="button primary" disabled={busy || !data} onClick={() => void command(position, "question")}>{game?.status === "question" ? "เริ่มเวลาใหม่" : position === 1 ? "เริ่มเกม" : "เริ่มข้อนี้"}</button><button className="button ghost" disabled={busy || !data || position >= 20} onClick={() => void command(position + 1, "question")}>ข้อต่อไป</button><button className="button ghost" disabled={busy || !data || game?.status !== "question"} onClick={() => void command(position, "paused")}>พักเกม</button><button className="button ghost" disabled={busy || !data || game?.status !== "question"} onClick={() => void command(position, "reveal")}>แสดงเฉลยข้อนี้</button><button className="button ghost" disabled={busy || !data} onClick={() => void command(position, "finished")}>จบเกม</button><button className="button ghost" disabled={!data} onClick={() => setShowAll((value) => !value)}>{showAll ? "แสดง Top 5" : "แสดงทุกคน"}</button>{room === "142426" && <button className="button danger-button" disabled={busy || !data} onClick={() => void resetTestRoom()}>รีเซ็ตห้องทดสอบ</button>}</div></div><div className="panel"><div className="eyebrow-small">LIVE LEADERBOARD</div><h2 style={{ fontFamily: "Cormorant Garamond", fontSize: "2rem", margin: "8px 0 14px" }}>{showAll ? "All players" : "Top 5"}</h2>{data && displayedRanks.length === 0 ? <p className="waiting">ยังไม่มีผู้เล่นเข้าห้อง</p> : <ol className="rank-list">{displayedRanks.map((player, index) => <li key={`${player.nickname}-${index}`}><span>#{index + 1} {player.nickname}</span><strong>{player.score}</strong></li>)}</ol>}</div></div></section></main>;
}

function HostMonitor({ game, players, ready, answered, seconds }: { game?: HostState["state"]["room"]; players: number; ready: number; answered: number; seconds: number }) { const status = game?.status; return <section className="host-monitor" aria-live="polite"><div className="host-monitor-head"><span>LIVE GAME MONITOR</span><strong className={`host-phase ${status ?? "offline"}`}>{status ? statusCopy[status] : "ยังไม่เชื่อมห้อง"}</strong></div><div className="host-monitor-main"><b>{game ? `ข้อ ${String(game.currentPosition).padStart(2, "0")} / 20` : "—"}</b>{status === "question" ? <em>{seconds} <small>SEC</small></em> : <em>{status === "reveal" ? "เฉลย" : status === "lobby" ? "Lobby" : status === "finished" ? "Finish" : "Paused"}</em>}</div><div className="host-monitor-stats"><span><b>{players}</b> คนในห้อง</span><span><b>{ready}</b> พร้อมแล้ว</span><span><b>{answered}</b> ส่งคำตอบ</span></div><p>{status === "question" ? "ผู้เล่นกำลังตอบ · จะแสดงเฉลยอัตโนมัติเมื่อหมดเวลา" : status === "reveal" ? "ผู้เล่นกำลังดูเฉลยและคะแนน · Host เลือกข้อถัดไปได้เมื่อพร้อม" : status === "lobby" ? "รอผู้เล่นกด “ฉันพร้อมแล้ว” แล้วเริ่มเกม" : "สถานะเกมอัปเดตจากห้องจริง"}</p></section>; }
